# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: 
- chiyu_lin
pool:
  vmImage: ubuntu-latest

stages:
- stage: 'CodeQuality'
  jobs:
  - job: 'TestCode'
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.9'
      displayName: 'Use Python 3.9'

    - script: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      displayName: 'Install dependencies'

    - script: |
        python -m pytest -v --cov --cov-report=term-missing --cov-report=xml:coverage.xml
      displayName: 'Unit Tests'

    - task: SonarCloudPrepare@1
      inputs:
        SonarCloud: 'SonarCloud-BootCamp'
        organization: 'asus-aics'
        scannerMode: 'CLI'
        configMode: 'file'

    - task: SonarCloudAnalyze@1
      displayName: 'Run Code Analysis'
    - task: SonarCloudPublish@1
      inputs:
        pollingTimeoutSec: '300'

- stage: 'PublishArtifact'
  jobs:
  - job: 'PublishArtifact'

    steps:
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Pipeline.Workspace)'
        artifact: 'ptt-app-art'
        publishLocation: 'pipeline'

